### ISSUE TITLE
Setting Recursive = true in WatchSettings results in no changes being given.

### ISSUE THREAD

**Issue by Lattyware** [cake-addin/cake-watch#5]
Repro steps:
- Take the files from 'Example'.
- Change the first line to `#addin "nuget:?package=Cake.Watch"`
- Change the first argument to `new WatchSettings()`, run build.sh.
- Make changes in `hello.js`, see changes written to console.
- Change the first argument to `new WatchSetttings {Recursive = true}`, run build.sh.
- Make changes in `hello.js`, see no changes in console.

I'm on Arch Linux. Tried to take a look myself, and this appears to pass through to the `FileSystemWatcher`, so this may be an upstream bug.

**Comment by wk-j** [comment]
Hi @Lattyware 

I can't reproduce your issue

```csharp
#addin "nuget:?package=Cake.Watch"

Task("Watch-Inside").Does(() => {
    var settings = new WatchSettings { Recursive = true };
    Watch(settings , (changes) => {
        var list = changes.ToList();
        list.ForEach(x => {
            Console.WriteLine("{2} {0} {1}", x.Status, x.Name, DateTime.Now);
        });
    });
});

var target = Argument("target", "Watch");
RunTarget(target);
```

This script is work on my environment (Mono 4.6.1 + Ubuntu)
if issue come with Mono or Arch Linux I don't have ideas how to solve this.

```
# mono --version
Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Wed Oct 12 09:10:37 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

**Comment by wk-j** [comment]
Maybe I'm wrong

I can reproduce now, on Mono 4.6.1 + Ubuntu is same as you report
But I still have no ideas how to solve this issue.

**Comment by Lattyware** [comment]
Yeah, when I took a look, you are basically just passing through the attribute, so this is probably a bug in Mono or something. I'm grabbing a git version of Mono now to see if that works.

For completeness, I'm on a slightly older version of Mono, and Arch is rolling, so it's just current: 

```
± mono --version
Mono JIT compiler version 4.6.1 (Stable 4.6.1.3/abb06f1 Mon Oct  3 07:51:42 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
± cat /etc/*release*
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by Lattyware** [comment]
So I tried with the latest version, got the same result. If it is a mono bug, it appears to still be there. I also had a friend try on Windows using the `-mono` flag, and it works there, so it looks like it might be Linux-specific.

```
) mono --version
Mono JIT compiler version 4.9.0 (master/213499e Thu 13 Oct 13:54:11 BST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by Lattyware** [comment]
I found a workaround - setting `export MONO_MANAGED_WATCHER=false` will cause this to start working.

[The docs](http://mapsbkp.geolives.com/monodoc/index.aspx?link=T%3ASystem.IO.FileSystemWatcher) say:

> Mono's implementation of the FileSystemWatcher has multiple backends. This is necessary because not all operating systems supported by Mono have all the features necessary to provide the functionality expected by applications.
> 
> If the operating system kernel supports watching directories (inotify on Linux, KEvents on BSD or OSX) that feature is used; Otherwise it falls back to using the Gamin or FAM libraries (these libraries provide an API to monitor directories) and if none of those features are available, Mono will poll every 750 milliseconds the directories watched.
> 
> You can force the polling behavior (instead of using the kernel support) by setting the MONO_MANAGED_WATCHER environment variable before executing your application. This might be useful for filesystems that do not support inotify and still require polling to detect changes.

I am on a kernel version that definitely should have inotify support (4.7.5), so not sure what is going wrong here.

**Comment by wk-j** [comment]
Yes, use `MONO_MANAGED_WATCHER=false` also working on this environment.

```
# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```
But, have you look in to source code?

https://github.com/mono/mono/blob/master/mcs/class/System/System.IO/FileSystemWatcher.cs

I see nothing link to `MONO_MANAGED_WATCHER=false` here, its make me confuse again.

**Comment by Lattyware** [comment]
I believe it's line 115: `string managed = Environment.GetEnvironmentVariable ("MONO_MANAGED_WATCHER");`.
